name: Build WaterStrap
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Build
        run: dotnet publish Bloxstrap/Bloxstrap.csproj -c Release -r win-x64 --self-contained -o publish
      - uses: actions/upload-artifact@v4
        with:
          name: WaterStrap
          path: publish/*.exe
